import {openAi} from './openai'
import { Document } from 'langchain/document'
import { MemoryVectorStore } from 'langchain/vectorstores/memory'
import { OpenAIEmbeddings } from '@langchain/openai'
import {CharacterTextSplitter} from 'langchain/textsplitter'
import {PDFLoader} from 'langchain/document_loaders/fs/buffer'